USE [OICAR]
GO
/****** Object:  Table [dbo].[ACTIVITY]    Script Date: 13.5.2024. 11:30:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACTIVITY](
	[ID_ACTIVITY] [int] IDENTITY(1,1) NOT NULL,
	[KORISNIK_ID] [int] NOT NULL,
	[TARGET_ID] [int] NOT NULL,
	[ACTIVITY_TYPE_ID] [int] NOT NULL,
	[ACTIVITY_TIMESTAMP] [timestamp] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_ACTIVITY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ACTIVITY_TYPE]    Script Date: 13.5.2024. 11:30:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ACTIVITY_TYPE](
	[ID_ACTIVITY_TYPE] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_ACTIVITY_TYPE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CONVERSATION]    Script Date: 13.5.2024. 11:30:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CONVERSATION](
	[ID_CONVERSATION] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [int] NOT NULL,
	[MESSAGE_ID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_CONVERSATION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[COUNTRY]    Script Date: 13.5.2024. 11:30:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COUNTRY](
	[ID_COUNTRY] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_COUNTRY] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FOLLOW]    Script Date: 13.5.2024. 11:30:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FOLLOW](
	[ID_FOLLOW] [int] IDENTITY(1,1) NOT NULL,
	[FOLLOWED_USER_ID] [int] NOT NULL,
	[FOLLOWING_USER_ID] [int] NOT NULL,
	[FOLLOWING_TIMESTAMP] [timestamp] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_FOLLOW] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[KORISNIK]    Script Date: 13.5.2024. 11:30:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KORISNIK](
	[ID_USER] [int] IDENTITY(1,1) NOT NULL,
	[USERNAME] [nvarchar](50) NOT NULL,
	[FIRST_NAME] [nvarchar](50) NOT NULL,
	[LAST_NAME] [nvarchar](50) NOT NULL,
	[PASSWORD] [nvarchar](150) NOT NULL,
	[EMAIL] [nvarchar](100) NOT NULL,
	[COUNTRY_ID] [int] NOT NULL,
	[GENDER] [nvarchar](1) NOT NULL,
	[BIRTHDAY] [date] NOT NULL,
	[IMAGE] [nvarchar](max) NULL,
	[REGISTER_TIMESTAMP] [timestamp] NOT NULL,
	[IS_DELETED] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_USER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MESSAGE]    Script Date: 13.5.2024. 11:30:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MESSAGE](
	[ID_MESSAGE] [int] IDENTITY(1,1) NOT NULL,
	[SENDER_ID] [int] NOT NULL,
	[RECEIVER_ID] [int] NOT NULL,
	[MESSAGE_CONTENT] [nvarchar](160) NOT NULL,
	[MESSAGE_TIMESTAMP] [timestamp] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_MESSAGE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[POST]    Script Date: 13.5.2024. 11:30:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[POST](
	[ID_POST] [int] IDENTITY(1,1) NOT NULL,
	[USER_ID] [int] NOT NULL,
	[POST_TITLE] [nvarchar](50) NULL,
	[POST_CONTENT] [nvarchar](160) NOT NULL,
	[IMAGE] [nvarchar](max) NULL,
	[UPDATE_DATETIME] [smalldatetime] NULL,
	[DELETE_DATETIME] [smalldatetime] NULL,
	[IS_PUBLIC] [int] NOT NULL,
	[IS_PERMANENT] [int] NOT NULL,
	[DISAPEAR_DATETIME] [smalldatetime] NULL,
	[IS_DELETED] [int] NULL,
	[POSTING_DATETIME] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_POST] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[POST_COMMENT]    Script Date: 13.5.2024. 11:30:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[POST_COMMENT](
	[ID_COMMENT] [int] IDENTITY(1,1) NOT NULL,
	[POST_ID] [int] NOT NULL,
	[USER_ID] [int] NOT NULL,
	[COMMENT_CONTENT] [nvarchar](160) NOT NULL,
	[UPDATE_DATETIME] [smalldatetime] NULL,
	[DELETE_DATETIME] [smalldatetime] NULL,
	[COMMENTING_DATETIME] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_COMMENT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[POST_LIKE]    Script Date: 13.5.2024. 11:30:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[POST_LIKE](
	[ID_LIKE] [int] IDENTITY(1,1) NOT NULL,
	[POST_ID] [int] NOT NULL,
	[USER_ID] [int] NOT NULL,
	[LIKE_TIMESTAMP] [timestamp] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_LIKE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ACTIVITY]  WITH CHECK ADD FOREIGN KEY([ACTIVITY_TYPE_ID])
REFERENCES [dbo].[ACTIVITY_TYPE] ([ID_ACTIVITY_TYPE])
GO
ALTER TABLE [dbo].[ACTIVITY]  WITH CHECK ADD FOREIGN KEY([KORISNIK_ID])
REFERENCES [dbo].[KORISNIK] ([ID_USER])
GO
ALTER TABLE [dbo].[ACTIVITY]  WITH CHECK ADD FOREIGN KEY([TARGET_ID])
REFERENCES [dbo].[KORISNIK] ([ID_USER])
GO
ALTER TABLE [dbo].[CONVERSATION]  WITH CHECK ADD FOREIGN KEY([MESSAGE_ID])
REFERENCES [dbo].[MESSAGE] ([ID_MESSAGE])
GO
ALTER TABLE [dbo].[CONVERSATION]  WITH CHECK ADD FOREIGN KEY([USER_ID])
REFERENCES [dbo].[KORISNIK] ([ID_USER])
GO
ALTER TABLE [dbo].[FOLLOW]  WITH CHECK ADD FOREIGN KEY([FOLLOWED_USER_ID])
REFERENCES [dbo].[KORISNIK] ([ID_USER])
GO
ALTER TABLE [dbo].[FOLLOW]  WITH CHECK ADD FOREIGN KEY([FOLLOWING_USER_ID])
REFERENCES [dbo].[KORISNIK] ([ID_USER])
GO
ALTER TABLE [dbo].[KORISNIK]  WITH CHECK ADD FOREIGN KEY([COUNTRY_ID])
REFERENCES [dbo].[COUNTRY] ([ID_COUNTRY])
GO
ALTER TABLE [dbo].[MESSAGE]  WITH CHECK ADD FOREIGN KEY([RECEIVER_ID])
REFERENCES [dbo].[KORISNIK] ([ID_USER])
GO
ALTER TABLE [dbo].[MESSAGE]  WITH CHECK ADD FOREIGN KEY([SENDER_ID])
REFERENCES [dbo].[KORISNIK] ([ID_USER])
GO
ALTER TABLE [dbo].[POST]  WITH CHECK ADD FOREIGN KEY([USER_ID])
REFERENCES [dbo].[KORISNIK] ([ID_USER])
GO
ALTER TABLE [dbo].[POST_COMMENT]  WITH CHECK ADD FOREIGN KEY([POST_ID])
REFERENCES [dbo].[POST] ([ID_POST])
GO
ALTER TABLE [dbo].[POST_COMMENT]  WITH CHECK ADD FOREIGN KEY([USER_ID])
REFERENCES [dbo].[KORISNIK] ([ID_USER])
GO
ALTER TABLE [dbo].[POST_LIKE]  WITH CHECK ADD FOREIGN KEY([POST_ID])
REFERENCES [dbo].[POST] ([ID_POST])
GO
ALTER TABLE [dbo].[POST_LIKE]  WITH CHECK ADD FOREIGN KEY([USER_ID])
REFERENCES [dbo].[KORISNIK] ([ID_USER])
GO
